/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.ubt.ai7.csv_validator.services.SculptGrammarAccess;

public class SculptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SculptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.ubt.ai7.csv_validator.parser.antlr.internal.InternalSculptParser createParser(XtextTokenStream stream) {
		return new de.ubt.ai7.csv_validator.parser.antlr.internal.InternalSculptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Sculpt";
	}
	
	public SculptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SculptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
