/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SculptAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/ubt/ai7/csv_validator/parser/antlr/internal/InternalSculpt.tokens");
	}
}
