/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SculptUiModule extends de.ubt.ai7.csv_validator.ui.AbstractSculptUiModule {
	public SculptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
