/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.ui.contentassist

import de.ubt.ai7.csv_validator.ui.contentassist.AbstractSculptProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SculptProposalProvider extends AbstractSculptProposalProvider {
}
