/**
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class SculptQuickfixProvider extends DefaultQuickfixProvider {
}
