/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SculptRuntimeModule extends de.ubt.ai7.csv_validator.AbstractSculptRuntimeModule {

	/*
	// contributed by org.eclipse.xtext.generator.validation.ValidatorFragment
	@org.eclipse.xtext.service.SingletonBinding(eager=false)	public Class<? extends de.ubt.ai7.csv_validator.validation.SculptValidator> bindSculptValidator() {
		return de.ubt.ai7.csv_validator.library.SculptCsvRelationItem.class;
	}
	*/
}
