/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SculptStandaloneSetup extends SculptStandaloneSetupGenerated{

	public static void doSetup() {
		new SculptStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

