/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.ubt.ai7.csv_validator.ui.internal.SculptActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SculptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SculptActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SculptActivator.getInstance().getInjector(SculptActivator.DE_UBT_AI7_CSV_VALIDATOR_SCULPT);
	}
	
}
