/**
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.serializer;

import de.ubt.ai7.csv_validator.serializer.AbstractSculptSyntacticSequencer;

@SuppressWarnings("all")
public class SculptSyntacticSequencer extends AbstractSculptSyntacticSequencer {
}
