/**
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator.serializer;

import de.ubt.ai7.csv_validator.serializer.AbstractSculptSemanticSequencer;

@SuppressWarnings("all")
public class SculptSemanticSequencer extends AbstractSculptSemanticSequencer {
}
