/*
 * generated by Xtext
 */
package de.ubt.ai7.csv_validator;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SculptUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return de.ubt.ai7.csv_validator.ui.internal.SculptActivator.getInstance().getInjector("de.ubt.ai7.csv_validator.Sculpt");
	}

}
